/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'addArray' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addInt' : IDL.Func([IDL.Text, IDL.Int], [], []),
  'addLet' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addLetRec' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addNat' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'addVarArray' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'evaluate' : IDL.Func(
      [IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({ 'value' : IDL.Text, 'typeStr' : IDL.Text }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'freshVar' : IDL.Func([], [IDL.Text], []),
  'getEnv' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))], []),
  'reset' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'addArray' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addInt' : IDL.Func([IDL.Text, IDL.Int], [], []),
    'addLet' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addLetRec' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addNat' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'addVarArray' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'evaluate' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({ 'value' : IDL.Text, 'typeStr' : IDL.Text }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'freshVar' : IDL.Func([], [IDL.Text], []),
    'getEnv' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))], []),
    'reset' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };