/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface _SERVICE {
  'addArray' : ActorMethod<[string, string, string], undefined>,
  'addInt' : ActorMethod<[string, bigint], undefined>,
  'addLet' : ActorMethod<[string, string, string], undefined>,
  'addLetRec' : ActorMethod<[string, string, string], undefined>,
  'addNat' : ActorMethod<[string, bigint], undefined>,
  'addVarArray' : ActorMethod<[string, string, string], undefined>,
  'evaluate' : ActorMethod<
    [string],
    { 'ok' : { 'value' : string, 'typeStr' : string } } |
      { 'err' : string }
  >,
  'freshVar' : ActorMethod<[], string>,
  'getEnv' : ActorMethod<[], Array<[string, string]>>,
  'reset' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];